---
- name: update period
  command: radosgw-admin --cluster={{ cluster }} period update --commit

- name: restart rgw
  service:
    name: ceph-radosgw@rgw.{{ ansible_hostname }}
    state: restarted
